
INSERT INTO public.events (title, description, location, venue_name, coordinates, start_date, end_date, category, tags, image_url, pricing, accessibility, address_details, created_by, verification_status, is_featured)
VALUES
-- Luxembourg
('Schueberfouer Night Lights', 'Luxembourg''s historic funfair lights up the Glacis with rides, food stalls and live music. A must-see late-summer tradition.', 'Glacis, Luxembourg City', 'Champ du Glacis', point(6.1296, 49.6177), now() + interval '10 days', now() + interval '10 days 6 hours', ARRAY['Festival','Family','Music'], ARRAY['funfair','tradition','outdoor'], 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=1200&q=80', '{"isFree": true}'::jsonb, '{"languages":["fr","de","en"],"familyFriendly":true,"wheelchairAccessible":true}'::jsonb, '{"city":"Luxembourg City","country":"Luxembourg"}'::jsonb, '634a890e-df73-45ed-9f60-956a6c45a75c', 'verified', true),
('MeYouZik World Music Festival', 'Free open-air world music festival in the heart of Luxembourg City with artists from five continents.', 'Place Guillaume II, Luxembourg', 'Place Guillaume II', point(6.1319, 49.6116), now() + interval '20 days', now() + interval '22 days', ARRAY['Music','Festival','Cultural'], ARRAY['world-music','free','live'], 'https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=1200&q=80', '{"isFree": true}'::jsonb, '{"languages":["fr","en"],"familyFriendly":true,"wheelchairAccessible":true}'::jsonb, '{"city":"Luxembourg City","country":"Luxembourg"}'::jsonb, '634a890e-df73-45ed-9f60-956a6c45a75c', 'verified', false),

-- Nice, France
('Carnaval de Nice — Flower Parade', 'One of the world''s most famous carnivals takes over Place Masséna with flower-covered floats and street performers.', 'Place Masséna, Nice', 'Place Masséna', point(7.2720, 43.6975), now() + interval '5 days', now() + interval '5 days 4 hours', ARRAY['Festival','Cultural','Family'], ARRAY['carnival','parade','riviera'], 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=1200&q=80', '{"isFree": false, "priceRange":[15,45]}'::jsonb, '{"languages":["fr","en","it"],"familyFriendly":true,"wheelchairAccessible":true}'::jsonb, '{"city":"Nice","country":"France"}'::jsonb, '634a890e-df73-45ed-9f60-956a6c45a75c', 'verified', true),
('Nice Jazz Festival — Open Air', 'Legendary jazz festival under the olive trees of the Théâtre de Verdure with international headliners.', 'Théâtre de Verdure, Nice', 'Théâtre de Verdure', point(7.2746, 43.6961), now() + interval '30 days', now() + interval '34 days', ARRAY['Music','Festival'], ARRAY['jazz','open-air','live'], 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=1200&q=80', '{"isFree": false, "priceRange":[35,90]}'::jsonb, '{"languages":["fr","en"],"familyFriendly":true,"wheelchairAccessible":true}'::jsonb, '{"city":"Nice","country":"France"}'::jsonb, '634a890e-df73-45ed-9f60-956a6c45a75c', 'verified', false),

-- Paris, France
('Fête de la Musique — République', 'France''s nationwide music day. Free concerts on every street corner — meet the community at République.', 'Place de la République, Paris', 'Place de la République', point(2.3631, 48.8676), now() + interval '15 days', now() + interval '15 days 8 hours', ARRAY['Music','Festival','Community'], ARRAY['free','live','street'], 'https://images.unsplash.com/photo-1501281668745-f7f57925c3b4?w=1200&q=80', '{"isFree": true}'::jsonb, '{"languages":["fr","en"],"familyFriendly":true,"wheelchairAccessible":true}'::jsonb, '{"city":"Paris","country":"France"}'::jsonb, '634a890e-df73-45ed-9f60-956a6c45a75c', 'verified', true),
('Nuit Blanche Paris', 'All-night contemporary art festival across museums, galleries and public spaces.', 'Centre Pompidou area, Paris', 'Centre Pompidou', point(2.3522, 48.8606), now() + interval '40 days', now() + interval '40 days 12 hours', ARRAY['Art','Cultural'], ARRAY['art','night','exhibition'], 'https://images.unsplash.com/photo-1493514789931-586cb221d7a7?w=1200&q=80', '{"isFree": true}'::jsonb, '{"languages":["fr","en"],"familyFriendly":true,"wheelchairAccessible":true}'::jsonb, '{"city":"Paris","country":"France"}'::jsonb, '634a890e-df73-45ed-9f60-956a6c45a75c', 'verified', false),

-- Catania, Italy
('Festa di Sant''Agata', 'Catania''s historic patron-saint festival — one of the largest religious processions in the world.', 'Piazza Duomo, Catania', 'Cattedrale di Sant''Agata', point(15.0873, 37.5024), now() + interval '7 days', now() + interval '9 days', ARRAY['Cultural','Festival','Family'], ARRAY['tradition','procession','sicily'], 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=1200&q=80', '{"isFree": true}'::jsonb, '{"languages":["it","en"],"familyFriendly":true,"wheelchairAccessible":false}'::jsonb, '{"city":"Catania","country":"Italy"}'::jsonb, '634a890e-df73-45ed-9f60-956a6c45a75c', 'verified', true),
('Etna Sunrise Trek', 'Guided sunrise hike up Mount Etna with breakfast at the summit. Small groups, all levels welcome.', 'Rifugio Sapienza, Mount Etna', 'Rifugio Sapienza', point(15.0042, 37.7010), now() + interval '12 days', now() + interval '12 days 6 hours', ARRAY['Outdoor','Sports','Adventure'], ARRAY['hike','volcano','sunrise'], 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=1200&q=80', '{"isFree": false, "priceRange":[55,75]}'::jsonb, '{"languages":["it","en"],"familyFriendly":false,"wheelchairAccessible":false}'::jsonb, '{"city":"Catania","country":"Italy"}'::jsonb, '634a890e-df73-45ed-9f60-956a6c45a75c', 'verified', false),

-- Haarlem, Netherlands
('Haarlem Jazz & More', 'Three-day jazz, soul and pop festival in Haarlem''s historic Grote Markt.', 'Grote Markt, Haarlem', 'Grote Markt', point(4.6364, 52.3811), now() + interval '25 days', now() + interval '27 days', ARRAY['Music','Festival'], ARRAY['jazz','soul','live'], 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=1200&q=80', '{"isFree": true}'::jsonb, '{"languages":["nl","en"],"familyFriendly":true,"wheelchairAccessible":true}'::jsonb, '{"city":"Haarlem","country":"Netherlands"}'::jsonb, '634a890e-df73-45ed-9f60-956a6c45a75c', 'verified', false),
('Bloemencorso Bollenstreek — Haarlem Finale', 'The famous flower parade ends in Haarlem with floats covered in tulips and hyacinths.', 'Haarlem city center', 'Stationsplein Haarlem', point(4.6310, 52.3878), now() + interval '35 days', now() + interval '35 days 8 hours', ARRAY['Cultural','Family','Outdoor'], ARRAY['flowers','parade','spring'], 'https://images.unsplash.com/photo-1490750967868-88aa4486c946?w=1200&q=80', '{"isFree": true}'::jsonb, '{"languages":["nl","en"],"familyFriendly":true,"wheelchairAccessible":true}'::jsonb, '{"city":"Haarlem","country":"Netherlands"}'::jsonb, '634a890e-df73-45ed-9f60-956a6c45a75c', 'verified', true),

-- Amsterdam, Netherlands
('Amsterdam Light Festival — Canal Cruise', 'Glide through Amsterdam''s canals to see large-scale light artworks by international artists.', 'Amstel river, Amsterdam', 'Amstel Boarding Point', point(4.9041, 52.3676), now() + interval '18 days', now() + interval '18 days 2 hours', ARRAY['Art','Cultural','Family'], ARRAY['lights','canal','winter'], 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=1200&q=80', '{"isFree": false, "priceRange":[22,35]}'::jsonb, '{"languages":["nl","en"],"familyFriendly":true,"wheelchairAccessible":true}'::jsonb, '{"city":"Amsterdam","country":"Netherlands"}'::jsonb, '634a890e-df73-45ed-9f60-956a6c45a75c', 'verified', true),
('King''s Day Amsterdam — Vondelpark', 'The country turns orange. Street parties, free markets and live music across Vondelpark.', 'Vondelpark, Amsterdam', 'Vondelpark', point(4.8686, 52.3580), now() + interval '45 days', now() + interval '45 days 12 hours', ARRAY['Festival','Community','Family'], ARRAY['kingsday','orange','party'], 'https://images.unsplash.com/photo-1496337589254-7e19d01cec44?w=1200&q=80', '{"isFree": true}'::jsonb, '{"languages":["nl","en"],"familyFriendly":true,"wheelchairAccessible":true}'::jsonb, '{"city":"Amsterdam","country":"Netherlands"}'::jsonb, '634a890e-df73-45ed-9f60-956a6c45a75c', 'verified', false);
