// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://afdkepzhghdoeyjncnah.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFmZGtlcHpoZ2hkb2V5am5jbmFoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgyOTAyMjcsImV4cCI6MjA1Mzg2NjIyN30.eXHV-DvZPyEopTOkpK9LWHrcx1QEhUjAhvoonv718G0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);