// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Retrieve Supabase URL and Anon Key from Vite environment variables
// IMPORTANT: Only non-sensitive, public keys should be exposed to the frontend.
// The Supabase Anon Key is designed to be public. Ensure VITE_SUPABASE_URL is also appropriate for client-side exposure.
// Do NOT expose sensitive keys like Supabase service_role key or other private API keys here.
const VITE_SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const VITE_SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

// Validate that the environment variables are set
if (!VITE_SUPABASE_URL) {
  throw new Error("VITE_SUPABASE_URL is not set. Please check your .env file.");
}

if (!VITE_SUPABASE_ANON_KEY) {
  throw new Error("VITE_SUPABASE_ANON_KEY is not set. Please check your .env file.");
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(VITE_SUPABASE_URL, VITE_SUPABASE_ANON_KEY);